name: flutter_abuba
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  datetime_picker_formfield: ^0.1.8
  percent_indicator: ^1.0.13
  material_design_icons_flutter: ^3.0.3392
  flutter_circular_chart: ^0.1.0
  badges: ^0.0.6
  image_picker: ^0.5.0
  url_launcher: ^5.0.0
  smooth_star_rating: ^1.0.1
  flutter_swiper: ^1.1.4
  cloud_firestore: ^0.9.0
  firebase_core: ^0.3.1+1
  firebase_storage: ^2.0.1+1
  mailer: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/icon2.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/img_gojek_logo.png
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/logo_splash.png
    - assets/images/logo_splash2.png
    - assets/images/logo_light.png
    - assets/images/map.png
    - assets/images/map_2.png
    - assets/images/open_door.jpg
    - assets/images/slide greet.jpg
    - assets/images/slide 4.png
    - assets/images/slide 4copy.png
    - assets/images/slide 7.png
    - assets/images/slide 8.png
    - assets/images/slide 11.png
    - assets/images/slide 12.png
    - assets/images/slide 13.png
    - assets/images/slide 14.png
    - assets/images/slide 15.png
    - assets/images/slide 16.png
    - assets/images/slide 18.png
    - assets/images/slide 19.png
    - assets/images/slide 21.png
    - assets/images/slide 23.png
    - assets/images/slide 24.png
    - assets/images/slide 25.png
    - assets/images/slide 26.png
    - assets/images/slide2.png
    - assets/images/slide3.png
    - assets/images/abuba1.jpg
    - assets/images/abuba2.jpg
    - assets/images/abuba3.jpg
    - assets/images/abuba4.jpg
    - assets/images/abuba5.jpg
    - assets/images/abuba6.jpg
    - assets/images/Billing.jpeg
    - assets/images/Greeting.jpeg
    - assets/images/Pre Bushing.jpeg
    - assets/images/Seating.jpeg
    - assets/images/Taking Order.jpeg
    - assets/images/benchmark.png
    - assets/images/mg.png
    - assets/images/report.png
    - assets/images/start_review.png
    - assets/images/outlet_performance.png
  fonts:
    - family: NeoSans
      fonts:
        - asset: assets/fonts/Neo Sans Std Medium TR.otf
    - family: NeoSansBold
      fonts:
        - asset: assets/fonts/Neo Sans Std Medium TR.otf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
